### ISSUE TITLE
貌似下载不了jar包

### ISSUE THREAD

**Issue by HuaZaiWuDi** [aicareles/AopArms#1]
# #

**Comment by aicareles** [comment]
看下报什么问题，是不是网络环境问题

**Comment by HuaZaiWuDi** [comment]
就是没找到库文件啊，你依赖的是什么仓库？

**Comment by aicareles** [comment]
加QQ群讨论，494309361  Android开发小纵队

**Comment by HuaZaiWuDi** [comment]
![image](https://user-images.githubusercontent.com/26106636/60088821-e3c5cb00-9771-11e9-8047-1fe96b655022.png)
![image](https://user-images.githubusercontent.com/26106636/60088831-e9bbac00-9771-11e9-982e-39bec59520f4.png)

**Comment by aicareles** [comment]
十分抱歉，直接提交到jCenter，还没有审核通过，现在可以了
