### ISSUE TITLE
部分类找不到

### ISSUE THREAD

**Issue by crazyandcoder** [aicareles/AopArms#5]
hi，作者你好

import cn.com.superLei.aoparms.annotation.Callback;

这个类找不到

**Comment by aicareles** [comment]
这个是最新版本的，抱歉，还没有更新到jcenter上

**Comment by crazyandcoder** [comment]
如果方便的话，请将该类发送到我的邮箱，谢谢～

**Comment by aicareles** [comment]
已经更新到Github了

**Comment by crazyandcoder** [comment]
谢谢
