### ISSUE TITLE
生命周期

### ISSUE THREAD

**Issue by ssyRo156** [aicareles/AopArms#7]
可以绑定生命周期取消回调？

**Comment by aicareles** [comment]
感谢你的建议,扫描-连接-设置通知等等回调不需要你主动处理移除监听的操作,比如您想扫描后,关闭页面后担心继续收到回调,你可以主动停止扫描,自动会被移除.&nbsp; 连接也是如此,如果点击连接后 还未连接成功,关闭页面,那么你同样 可以 调用cancelConnectting方法,当您断开连接后,通知的回调监听等自动移除,如果您想彻底移除并释放ble相关,则调用release接口




------------------&nbsp;原邮件&nbsp;------------------
发件人:&nbsp;"shimmer"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月2日(星期一) 下午2:02
收件人:&nbsp;"aicareles/AopArms"<AopArms@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[aicareles/AopArms] 生命周期 (#7)




可以绑定生命周期取消回调？

**Comment by ssyRo156** [comment]
谢谢您的回复



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Allen Iverson <notifications@github.com&gt;
发送时间: 2020年3月2日 17:34
收件人: aicareles/AopArms <AopArms@noreply.github.com&gt;
抄送: Neil <1757295192@QQ.COM&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[aicareles/AopArms] 生命周期 (#7)



感谢你的建议,扫描-连接-设置通知等等回调不需要你主动处理移除监听的操作,比如您想扫描后,关闭页面后担心继续收到回调,你可以主动停止扫描,自动会被移除.&amp;nbsp; 连接也是如此,如果点击连接后 还未连接成功,关闭页面,那么你同样 可以 调用cancelConnectting方法,当您断开连接后,通知的回调监听等自动移除,如果您想彻底移除并释放ble相关,则调用release接口 
 
 
 
 
 ------------------&amp;nbsp;原邮件&amp;nbsp;------------------ 
 发件人:&amp;nbsp;"shimmer"<notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年3月2日(星期一) 下午2:02 
 收件人:&amp;nbsp;"aicareles/AopArms"<AopArms@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;[aicareles/AopArms] 生命周期 (#7) 
 
 
 
 
 可以绑定生命周期取消回调？
